var fullName = 'moamel hashim';
console.log('value of fullName:', fullName);
console.log(typeof fullName);
var isCool = true;
console.log('value of isCool:', isCool);
console.log(typeof isCool);
var totalPets = 1;
console.log('value of totalPets:', totalPets);
console.log(typeof totalPets);
var unknown = null;
console.log('value of unknow:', unknown);
console.log(typeof unknown);
var never;
console.log('value of never:', never);
console.log(typeof never);
